version: '3.8'

services:
  app:
    build:
      context: src
      dockerfile: EPR.PRN.ObligationCalculation.Function/Dockerfile
      platforms:
        - linux/amd64
    environment:
      FUNCTIONS_WORKER_RUNTIME: "dotnet-isolated"
      AzureWebJobsStorage: "UseDevelopmentStorage=true"
      HOST: "localhost"
    ports:
      - "7071:80"
    healthcheck:
      test: ["CMD-SHELL", "timeout 2 bash -c '</dev/tcp/localhost/80' || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
